### ISSUE TITLE
Unreal Engine support for Colyseus

### ISSUE THREAD

**Issue by HeadClot** [colyseus/colyseus#16]
Hey @endel -

Got a bit of a request for an enhancement for Colyseus. Would it be possible to get a Unreal 4 integration going using [Unreal.JS](https://github.com/ncsoft/Unreal.js/) and the Unreal [Socket.io](https://github.com/getnamo/socketio-client-ue4) plugin for Unreal?

Thanks for your time,

Benjamin

**Comment by endel** [comment]
Hi @HeadClot, 

It would be great indeed! I'm not so experienced with C++ to implement that, though. 
We'd need a plain WebSocket implementation (not socket.io), MsgPack, JSON Patching and the binary delta algorithm.

At this very moment, I'm still working on the Unity3D client to match the last server version (https://github.com/gamestdio/colyseus-unity3d/issues/2).

If someone has the interest to create the new client I'd be very glad :)

Thanks for your interest in the project,
Cheers!

**Comment by jesst3r** [comment]
Endel, i'm planning to do the same, so i can share client Cpp static library for the colyseus, in the nearest future (WIP now)

**Comment by endel** [comment]
@jesst3r wonderful. If you can give a starting point for this library maybe I could help. Cheers!

**Comment by endel** [comment]
The most challenging task on the client side is the deep object diff algorithm. This is still missing in the Unity3d client. (https://github.com/gamestdio/colyseus-unity3d/issues/2)

I'll quote here just to make things clear  (https://github.com/gamestdio/colyseus-unity3d/issues/2#issuecomment-258700254)

> The server v0.3.x used to send the patch list directly as [JSON patch format](https://tools.ietf.org/html/rfc6902), which was then simply applied in the client-side. This has been changed in version v0.4.x - the patched state is now sent in a [binary compressed format](https://www.fossil-scm.org/index.html/doc/trunk/www/delta_format.wiki), which is faster to compute has smaller throughput. This change made unnecessary to use JSON at all in the Unity client.

For the JavaScript client this is not a problem, since there's [more](https://github.com/flitbit/diff) than [one](https://github.com/Starcounter-Jack/JSON-Patch) implementation already available for evaluating the difference between objects.

For Unity3d, it requires an effort but it would be possible to implement the JSON-Patch comparison algorithm against the decoded msgpack result. The C++ approach could be similar.

Maybe there's a different way to approach this that I'm not aware of. I'd love to hear your thoughts about this.

**Comment by endel** [comment]
Our fellow @chunho32 implemented a Cpp/Cocos2d-x client! 🎉 

I guess it would be possible to use it for Unreal projects as well? https://github.com/chunho32/colyseus-cocos2d-x

**Comment by trollr** [comment]
Any news here? We want to use the unreal engine with colyseus too. However before we start to develop our own colyseus plugin i want to ask if someone already started to develop one

**Comment by endel** [comment]
Hi @trollr, there's no Unreal Engine client available yet, the [cocos2d client](https://github.com/chunho32/colyseus-cocos2d-x) can be used for reference, but keep in mind it's a bit outdated. 

I'd suggest using the JavaScript/HTML5 client as a major reference for implementing new clients since the community has been using it the most.

(It **might** be possible to use the CPP output from the [Haxe client](https://github.com/gamestdio/colyseus-hx) to use inside Unreal, I'm not sure if it's possible neither if it's a good idea)

**Comment by endel** [comment]
Closing as this should be tracked on https://github.com/colyseus/colyseus/issues/217
