### ISSUE TITLE
MemsharedPresence room issue

### ISSUE THREAD

**Issue by Loonride** [colyseus/colyseus#201]
## Steps to Reproduce and Context

1. I am trying to use MemsharedPresence to scale across multiple processes, similar to this example: https://github.com/gamestdio/colyseus/blob/master/usage/ServerCluster.ts
2. Here is what I am testing it with: https://github.com/Loonride/colyseus-cluster-example (you can do npm install, then npm run dev)
3. The server works fine without the presence: new colyseus.MemsharedPresence() line.
4. With that line included, initial connection with the server succeeds (onOpen is emitted), but after that, the attempt to connect with the room seems to hang and emits no events on the client (eg. onJoin, onLeave, onError)

## Your Environment

* Colyseus Version: 0.9.19
* Node.js Version: 8.9.4
* Operating System and version: Windows 7
* Link to your project: https://github.com/Loonride/colyseus-cluster-example

**Comment by endel** [comment]
Hi @Loonride, thanks for sharing the repo. I've managed to reproduce on OSX too.

The problem seems to be in the detection of the master node [memshared performs here](https://github.com/endel/memshared/blob/d5e74a7ca9e97afdbaae0ad90e55a35aff6c989c/src/index.ts#L56-L58)

When starting the server through `nodemon` directly it identifies correctly, though:

```
cd server
nodemon index.js
```

I'm not sure what'd be necessary to allow memshared to work along with [`concurrently`](https://github.com/Loonride/colyseus-cluster-example/blob/9d9b22102100f93a51fbf3f480c2df293777bf8d/package.json#L10).

**Comment by endel** [comment]
The `MemsharedPresence` has been deprecated. The de-facto solution for scalability is still not 100% sorted out, for now, this is the way to go: https://github.com/colyseus/proxy
