### ISSUE TITLE
BUG: Colyseus using fossil delta instead of schema

### ISSUE THREAD

**Issue by marwan38** [colyseus/colyseus#244]
## Steps to Reproduce (for bugs)
1. Clone this nice repo given to us by @endel https://github.com/endel/colyseus-pixijs-boilerplate.git
2. `npm i` then `npm run dev`
3. You should see these errors (which stem from colyseus trying to setState with fossil delta serializer): 
```
room.entities.players is undefined
Error: {num} trailing bytes
```
4. Update `colyseus` and `coyseusljs` to `latest@0.10.7` you will see same issue.
5. Run `npm i colyseus@0.10.3 colyseus.js@0.10.3` and then the project runs fine. 

## Context
I was moving my project from angular to use the boilerplate mentioned above as it was lighter.

## Your Environment
* Colyseus Version: 0.10.4+
* Node.js Version: v10.12.0
* Operating System and version: Windows 10
* Link to your project: N/A

**Comment by endel** [comment]
Thanks for reporting @marwan38! I just fixed this on latest `colyseus.js` (`0.10.8`)

I've added the ability to use a custom implementation of schemas in the client-side, which is not documented yet.

```typescript
class State extends Schema {
    // @type() ... your typed fields

    onChange(changes) {
      // handle client-side changes here
    }
}

var room = client.join<State>("room_name", {...options...}, State);
```

This new addition is experimental because now it's possible to have both server-side AND client-side logic within the schema classes, and having duplicated schema declarations on both sides can lead difficult code refactoring and increased attention when adding new fields to schema classes. Feedback is always welcome!
