### ISSUE TITLE
Calling `broadcast()` during `onJoin()` is ignoring the new client

### ISSUE THREAD

**Issue by endel** [colyseus/colyseus#260]
Reported by @damian-pastorini

**Comment by damian-pastorini** [comment]
I would say `is ignoring the current client` so:
```onJoin(()=>{ 
    this.broadcast // will never reach this client 
}```

**Comment by finkton1** [comment]
Any update on status of this bug?

**Comment by endel** [comment]
@finkton1 a workaround, for now, is to also call `this.send(client, /* data */)` along with `this.broadcast()` to include the joining client to receive that message, I'm going to post an update here when this gets fixed

**Comment by rnd256** [comment]
Possibly related to this bug: I've discovered that the first client joining a room never receives some nested state data that gets added in `onJoin`. Specifically in my case, a sub-object within a `MapSchema`.

The second client joining triggers this state change, and that client has no problem syncing the full state.

I've reproduced this behavior in both the JS and Unity clients, so the cause is likely server-side.
