### ISSUE TITLE
How can I match players with the same level?

### ISSUE THREAD

**Issue by Yinmany** [colyseus/colyseus#263]
Hey, I read the document, but I didn't understand it.

**Comment by damian-pastorini** [comment]
hi @Yinmany , Colyseus doesn't have any game logic, you will need to implement all that by yourself.

**Comment by endel** [comment]
If you have [`maxClients = 2`](https://docs.colyseus.io/server/room/#maxclients-number) for example, and two clients perform [client.joinOrCreate()](https://docs.colyseus.io/client/client/#joinorcreate-roomname-string-options-any), they should be matched together in the same "level".

**Comment by giraffesyo** [comment]
Are you trying to do matchmaking, like players of the same skill level?

**Comment by amit-gshe** [comment]
The room query criteria shold have more control to add some custom logic so we can set some custom match criteria by call room's `setMetadata` when one create a room. And then another one query available room with a specified metadata query or generaed by a function. This way we can first set a level in the metadata and then another player can query the room with its level (the level should be query out from database). But now the metadata was not included in the room query. @endel Is there any plan to add custom dynamic query criteria when one query available room?

**Comment by endel** [comment]
It would be really great to have this @amit-gshe, as @GDdark and @RonnyHou described on this issue: https://github.com/colyseus/colyseus/issues/259

Having more query options for matchmaking shouldn't be very difficult to make, I'd like its API to be reasonable before going ahead and implementing this. Now that version v0.11 has [`LocalDriver`](https://github.com/colyseus/colyseus/blob/5cab0fbd76621ff043ff08154ae71fde72227b71/src/matchmaker/drivers/LocalDriver/index.ts) and [`MongooseDriver`](https://github.com/colyseus/colyseus/blob/5cab0fbd76621ff043ff08154ae71fde72227b71/src/matchmaker/drivers/MongooseDriver.ts) for matchmaking, the querying API should work in a way that can be implemented on both drivers.

The `Room` class also has an undocumented [`listing` property](https://github.com/colyseus/colyseus/blob/5cab0fbd76621ff043ff08154ae71fde72227b71/src/Room.ts#L47) since v0.11, which holds the structure for matchmaking (the entry of `LocalDriver`/`MongooseDriver`). When you call `setMetadata()`, it operates on this `listing` instance.

Suggestions for the querying API from the client-side are welcome.

**Comment by amit-gshe** [comment]
The client can pass options to the server,but how to use the options is more of the server's business,so the server should have a point to use the options client passed to construct the query.
