### ISSUE TITLE
TypeError: Cannot read property '_onJoin' of undefined

### ISSUE THREAD

**Issue by GDdark** [colyseus/colyseus#277]
When the network connection time out.  It showed the error below.
How can I update the time out config??
 
![image](https://user-images.githubusercontent.com/15982894/67762858-55e05080-fa81-11e9-9dc0-0087659c995d.png)

Colyseus server version: 0.11.20
Node.js version: v10.15.1

**Comment by endel** [comment]
Hi @GDdark, this error is probably due to "seat reservation" being expired, and the room being disposed due to lack of clients connected to it. 

There are two ways to increase the seat reservation timeout:
- Setting a global environment variable: `COLYSEUS_SEAT_RESERVATION_TIME=20` (default value is `8`)
- Setting per-room, using `this.setSeatReservationTime(20)`

**Comment by HishamMubarak** [comment]
> Hi @GDdark, this error is probably due to "seat reservation" being expired, and the room being disposed due to lack of clients connected to it.
> 
> There are two ways to increase the seat reservation timeout:
> 
> * Setting a global environment variable: `COLYSEUS_SEAT_RESERVATION_TIME=20` (default value is `8`)
> * Setting per-room, using `this.setSeatReservationTime(20)`

Any specific reason for setting it to 20? Or just that it is a higher number than 8?
