### ISSUE TITLE
Performance Question with Phaser

### ISSUE THREAD

**Issue by Maeggi** [colyseus/colyseus#295]
Hi @ll,
i use:
Phaser 3 (Own Updatey-System)
Colyseus 0.11.29

The Game-Logic completely Server-Side, for Anti-Cheat.

The Performance is very good. But, every second i have a small lag.
Is really only a small lag, but totally annoying ^^
What can i do to counteract the Performance or lag?

Update on Colyseus is:
`this.setPatchRate(16.6)`

The Game has a constant 59-60 FPS

Sry, for my English :)

**Comment by endel** [comment]
Hi @Maeggi, what do you mean by a small lag? This can have many reasons. I'd suggest profiling your game using the developer tools, and check what is causing the hiccups in the client. https://developers.google.com/web/updates/2016/12/devtools-javascript-cpu-profile-migration

**Comment by Maeggi** [comment]
Hi @endel, maybe the Problem is my big Map (2400 x 2400 px).
The game runs smoothly, without Websockets.
Here a Profiling Screenshot:
https://www.minpic.de/i/9n18/11qiwe

**Comment by Maeggi** [comment]
I think that's because Phaser-Update and Colyseus are not syncron

**Comment by Maeggi** [comment]
Ok, a have check the "colyseus-pixijs-boilerplate", has the same effect "Background". Seems to be normal

**Comment by oyed** [comment]
@Maeggi When you say your Map is 2.4k x 2.4k, how does the server see the map?
Is it Tiled? E.g. 16x16 px Tiles making the map a 150x150 multi-dimensional array/map server-side? Or are you running an entire pixel-like physics system server-side?

The only way we can really help regarding this issue is if you give us as much information as possible - a reproduction repo is the best bet

**Comment by Maeggi** [comment]
Hi @oyed, 
The Server does not see the Map. The Map is an Image.
The Performance are better as Phaser-Tilemap.
The server has a collision-system (Players, Walls, Bullets). And the movements are processed on the Server-Side. That's all ...

Upload a very small example:
[Repo](https://github.com/Maeggi/test-game)

Thanks for Help

**Comment by bhgsbatista** [comment]
@Maeggi any chance you'd be willing to make a boilerplate repo that integrates Phaser with Colyseus? I'm currently working on something similar and it might make more sense to collaborate and build something that isn't game specific.

**Comment by Maeggi** [comment]
Hi @bhgsbatista, i don't have time for a collaborate Project. You can find other boilerplate on Github. Search for: colyseus phaser

**Comment by damian-pastorini** [comment]
hi @bhgsbatista , this is a bit more specific that a boilerplate (I'm working on a platform for mmorpg), but maybe it can help you: https://github.com/damian-pastorini/reldens
It has Colyseus, physics (P2JS), and Phaser integrated.

**Comment by bhgsbatista** [comment]
Thanks for sharing your work with me (and the rest of the open source community), unfortunately it's not a good fit for what I'm looking for. I'm looking for a boilerplate that is simpler and not so genre / game specific.

I'm also looking for something that uses TypeScript, since I think using Phaser and colyseus with TS is a pretty good experience and will only get better over time.

**Comment by damian-pastorini** [comment]
Yeah, I had TS in my mind for some time already but wanted to get something more complete before move to TS.
Would like to see if you find or share with the community a boilerplate for these in TS :)

**Comment by bhgsbatista** [comment]
Seems like I'll have to put one together, haven't found anything that comes close to what I want to do. Also after thinking a bit about things like sound effects, collision effects and client side movement / collision prediction like, a comprehensive generalized solution is clearly pretty complicated thing to do.

It's a problem I'm motivated to tackle, after totally failing to make a multiplayer game during the global game jam :-P

**Comment by damian-pastorini** [comment]
hi @bhgsbatista , you can join Colyseus or my project discord, I would love to chat about all this.
I've started my project just for that, make it easier to make multiplayer games, though initially I'm trying to handle an mmorpg mode, with not much modifications it can be used for other kind of multiplayer games since it already has collisions and a lot of integrations between the server/client using the server as authority. I didn't get into client prediction yet since it's on Colyseus plans at some point so I'll wait for it instead of doing a custom implementation when I still don't need.
