### ISSUE TITLE
A custom roomId error caused by multiple inherits

### ISSUE THREAD

**Issue by dengzhaofun** [colyseus/colyseus#299]
```
export class GameRoom extends Room {
  fsm: StateMachine.StateMachine;
  app: Application
  roomConfig: any;
  tableConfig: any;
  // When room is initialized
  async onCreate(options: any) {
    this.setPrivate(true)
    this.maxClients = 200;
    this.autoDispose = false;
    const roomId = await Container.get(RoomNumber).pop()
    if (!roomId) {
      throw new Error('not enough room number')
    }
    this.roomId = roomId
  }
}

export class PokerGame extends GameRoom {
}
```
If you define a GameRoom, the result is the expected roomId of the numeric type, but if you define a PokerGame then the roomId becomes the engine's default id rule.

**Comment by dengzhaofun** [comment]
Close the problem. This is my mistake. I forgot to add await to the onCreate of the derived class, which caused the function to exit early. Sorry.

**Comment by oyed** [comment]
Can you give us more information? E.g. why are you setting your own `roomId` instead of the default generation? What is `Container`? Where does `RoomNumber` come from?

`roomId` is set _after_ we initialize the `Room` Instance (See https://github.com/colyseus/colyseus/blob/master/src/MatchMaker.ts#L240) and stored against the _auto-generated ID_ within the Match Maker. We do not openly support manually overriding Room ID.

Perhaps if you need to query rooms by some sort of logic, use the built-in MatchMaker Filters (https://docs.colyseus.io/server/api/#matchmaking-filters-filterbyoptions)

**Comment by dengzhaofun** [comment]
@oyed The current development project requires the player to input the room number to enter. The room number is 6 digits, but the default of the engine does not meet the requirements. I do not want to create a mapping between redis id and roomId to increase the development complexity

**Comment by oyed** [comment]
@dengzhaofun That can still be achieved via the MatchMaking filters instead of overwriting the Room ID - we cannot guarantee future versions won't break your usage since it isn't something we support
