### ISSUE TITLE
I'm a little devastated.

### ISSUE THREAD

**Issue by dengzhaofun** [colyseus/colyseus#300]
I spent a whole day, lasting 20 hours without rest, trying to tap the development advantages that the engine can bring and the ability to automatically synchronize the state, the results were very unsatisfactory.I may want to change a game engine for project development.Summarize engine problems.

1. Room does not support deep inheritance
2. Schema does not support Date type
3. Schema does not support dynamic typing
4. The engine is not robust enough to cause crashes
5. Long connection does not support the request / response mode like http or pomelo
6. There are still many bugs

The ideal of the engine is full and the reality is very skinny

**Comment by oyed** [comment]
1. Please supply an example for debugging on our end
2. If you convert Date to unix/eopch timestamps and use an Integer, it should work perfectly fine
3. Due to the nature of the binary transport protocol, dynamic typing would make things much slower/more difficult
4. Please supply an example if you're encountering crashes
5. I'll leave this one to more experienced people to answer (@endel @seiyria)
6. Again, examples needed

**Comment by seiyria** [comment]
If you find bugs, please report specific bugs as separate issues so they can be tracked accordingly.

With 4 and 6, we _really_ need to have a use case or some way to understand what you're doing that's causing problems. Just saying "there are bugs" does not help anyone.
