### ISSUE TITLE
sessionID is repeated? It was not repeated before

### ISSUE THREAD

**Issue by oxDesigner** [colyseus/colyseus#375]
Your issue may already be reported!
Please search on the [issue tracker](../) before creating one.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Colyseus Version:
* Node.js Version:
* Operating System and version:
* Link to your project:

**Comment by endel** [comment]
Hi @oxDesigner, since version 0.11, `client.id` is just an alias to `client.sessionId` (https://docs.colyseus.io/migrating/0.11/#clientid-has-been-removed)

The reason for the removal of `client.id` is because it was not reliable. It was supposed to be a unique identifier PER USER, but that feature only increased complexity and possibly had security vulnerabilities. Cheers!
