### ISSUE TITLE
Lacking a method to list out all available rooms on server-side

### ISSUE THREAD

**Issue by tonygiang** [colyseus/colyseus#387]
There is currently no (known) way to get a list of all available rooms on server-side equivalent of `getAvailableRooms` on clients-side.

While the Matchmaker API provides `findOneRoomAvailable`, this method only returns 1 result and requires an additional options argument. Sometimes we would like the full, unfiltered list of rooms available.

This issue is very urgent for me and my work.

**Comment by endel** [comment]
Hi @tonygiang, what about `matchMaker.query()`? https://docs.colyseus.io/server/matchmaker/#queryconditions

You can query rooms by `{locked:false, private: false}` which should return exactly the same results as "available rooms" from the client-side.

Let me know if that works for you

**Comment by tonygiang** [comment]
That works, but now I have even more questions.

What fields are accepted in the conditions object? I noticed that `locked` and `private` are fields that don't even show up in the result.

How come this method doesn't consistently have an argument to filter room handle like `findOneRoomAvailable`?

Is there a built-in way to filter rooms in more complex conditions (get all rooms with handle other than XYZ, get all rooms with maxClients between 8 and 16, etc...) or is my choice limited to getting every room possible and filter them out later?

**Comment by endel** [comment]
The built-in fields all rooms may have are: https://github.com/colyseus/colyseus/blob/master/src/matchmaker/drivers/Driver.ts#L3-L12

There's not much documentation around this because I feel this area lacks some polishing and may change in the future:
- Request for MySQL support https://github.com/colyseus/colyseus/issues/275
- Request for more query operations: https://github.com/colyseus/colyseus/issues/259

Currently, you can only leverage more querying options by using the `MongooseDriver` and providing a MongoDB query object directly, like: `{ name: {$ne: "something"} , maxClients: { $gte: 8, $lte: 16 } }` (where `$ne` - not equal, `$gte` - greather than or equal, `$lte` - lesser than or equal)

```typescript
import { MongooseDriver } from "colyseus/lib/matchmaker/drivers/MongooseDriver"
const gameServer = new Server({
  // ...
  driver: new MongooseDriver(),
});
```

The `LocalDriver` does not currently support this. Before officially supporting query operations, I'd like to make sure they're going to work on every driver.

**Comment by tonygiang** [comment]
Can we query nested metadata in the conditions object?
