### ISSUE TITLE
`@colyseus/core` is missing a declaration file for `'debug'` (it may have a hidden dependency on `@types/debug`)

### ISSUE THREAD

**Issue by rnd256** [colyseus/colyseus#426]
After upgrading to Colyseus Version 0.14.20, `tsc` throws this error:

```
node_modules/@colyseus/core/build/Debug.d.ts(1,19): error TS7016: Could not find a declaration file for module 'debug'. '/app/node_modules/@colyseus/core/node_modules/debug/src/index.js' implicitly has an 'any' type.
Try `npm install @types/debug` if it exists or add a new declaration (.d.ts) file containing `declare module 'debug';`
```

## Your Environment
* Colyseus Version: 0.14.20
* Node.js Version: 14.17.4
* Typescript version: 4.0.2

**Comment by endel** [comment]
Hi @rnd256! Thanks for reporting, we're starting to recommend using `skipLibCheck` on `tsconfig.json`: https://github.com/colyseus/create-colyseus-app/blob/f49f886288f398276413b779cbe5c27615706deb/tsconfig.json#L11

It doesn't feel right to add `@types/debug` as a dependency because of this, I think there's no need for TypeScript to try to compile code that's not your own...

**Comment by rnd256** [comment]
Thanks @endel! I think the standard would be to add it as a devDependency in your package.json, but skipping lib check works for me :)
