### ISSUE TITLE
error TS2345: Argument of type 'typeof RankedLobbyRoom' is not assignable to parameter of type 'Type<Room<any, any>>

### ISSUE THREAD

**Issue by hdev72** [colyseus/colyseus#488]
hello dear friends
after i change colyseus version from 11 tp 14... im getting this error 

pls help me

src/index.ts:24:21 - error TS2345: Argument of type 'typeof RankedLobbyRoom' is not assignable to parameter of type 'Type<Room<any, any>>'.
  Construct signature return types 'RankedLobbyRoom' and 'Room<any, any>' are incompatible.
    The types of 'onMessage' are incompatible between these types.
      Type '(client: Client, data: any) => void' is not assignable to type '{ <T = any>(messageType: "*", callback: (client: Client, type: string | number, message: T) => void): any; <T = any>(messageType: string | number, callback: (client: Client, message: T) => void): any; }'.
        Types of parameters 'client' and 'messageType' are incompatible.
          Type '"*"' is not assignable to type 'Client'.

error line:
24   .define('ranked', RankedLobbyRoom)

My index.ts:

import http from "http";
import path from "path";
import express from "express";
import cors from "cors";
import { Server } from "colyseus";
import { monitor } from "@colyseus/monitor";

import { RankedLobbyRoom } from "./RankedLobbyRoom";
import { GameRoom } from "./GameRoom";

const port = Number(process.env.PORT || 2567);
const app = express()

app.use(cors());
app.use(express.json())

const server = http.createServer(app);
const gameServer = new Server({
  server,
});

// register your room handlers
gameServer
  .define('ranked', RankedLobbyRoom)
  .filterBy(['numClientsToMatch']);
  //.filterBy(['1']);

gameServer.define('game', GameRoom);

app.use(express.static(path.resolve(__dirname, "..")));

// register colyseus monitor AFTER registering your room handlers
app.use("/colyseus", monitor());

gameServer.listen(port);
console.log(`Listening on ws://localhost:${ port }`)

**Comment by endel** [comment]
Hi @hdev72, nice to see you're migrating towards the new version, we're about to release version 0.15 very soon, a blog post is going to follow with the announcement.

This error is because `onMessage()` works differently now, you can read about this breaking change here: https://docs.colyseus.io/colyseus/migrating/0.13/#onmessage-has-been-reworked

As you're migrating from 0.11 to 0.14, I'd recommend having a read to each of the particular "migrating" docs, and see what you're using to migrate properly:
- from 0.11 to 0.12 https://docs.colyseus.io/colyseus/migrating/0.12/
- from 0.12 to 0.13 https://docs.colyseus.io/colyseus/migrating/0.13/
- from 0.13 to 0.14 https://docs.colyseus.io/colyseus/migrating/0.14/

**Comment by hdev72** [comment]
thank you so much
problem resolved
