### ISSUE TITLE
Error: "refId" not found: 2

### ISSUE THREAD

**Issue by Sh1d0w** [colyseus/colyseus#495]
I've searched the issues of this repo and seems like this was already fixed a year ago, but it is happening for me on the latest version.

## Steps to Reproduce (for bugs)

1. Join new room
2. Do an action
3. Join another room of same type
4. Try to do the same action, from now on you will always see `Error: "refId" not found: 2` (with different numbers at the end).

## Your Environment

* Colyseus Version: 0.14.23
* Node.js Version: 17.4.0
* Operating System and version: macOS Monterey 12.1 (21C52)
* Link to your project: The project is private. I gave you permissions to both project UI and server. You need to start both then create new table, sit on seat leave, create new table and sit again.

**Comment by endel** [comment]
Hi @Sh1d0w, thanks for sharing, I've had a quick look over the sources and I suspect it is related to `@filterChildren()`. Will inspect further during the week

**Comment by Sh1d0w** [comment]
Thanks @endel 

I also suspected it as well, so I already tried to remove it before I opened the issue. It still reproduces the same issue.

I managed to narrow the issue to the Sit command. You can see my commits in the server repo. If you checkout the previous one from the latest it works without this error. But it does not works on the latest version.

The only difference is that in the commit that it works I nullify the seat property, where in the latest I just replace prop from it, because I can't null it as I need to keep the hand with the cards. I hope that sheds some light on the issue, I am not sure how to debug it from there.

**Comment by endel** [comment]
We had another report of this issue and prepared a fix for it on `@colyseus/schema@1.0.41`:  https://github.com/colyseus/schema/commit/45410801abefa92468222e1afe5946368bfab9b9

The root cause was initializing a child `Schema` instance as `null`:

```typescript
// ...
@type(ChildSchema) child: ChildSchema = null;
// ...
```

This caused the encoder to encode a `DELETE_AND_ADD` operation, which during decoding ended up unintentionally dropping/garbage-collecting the new instance assigned to it.

Can you confirm if `@colyseus/schema@1.0.41` fixes for you @Sh1d0w?

**Comment by Sh1d0w** [comment]
Thanks I will try to reproduce tomorrow 👍

**Comment by endel** [comment]
Do we have a repro scenario for this?
