### ISSUE TITLE
Bug: MatchMakeError - {{roomId}} is full when room not available

### ISSUE THREAD

**Issue by ShukantPal** [colyseus/colyseus#513]
Your issue may already be reported!
Please search on the [issue tracker](../) before creating one.

## Steps to Reproduce (for bugs)

We haven't been able to reproduce this bug. My diagnosis of the problem is:

1. The matchmaker has it's own [local cache](https://github.com/colyseus/colyseus/blob/85bacb8068adfc215eb53c12b1f0f681ae0bbd44/packages/core/src/MatchMaker.ts#L32) of rooms, while the [LocalDriver](https://github.com/colyseus/colyseus/blob/85bacb8068adfc215eb53c12b1f0f681ae0bbd44/packages/core/src/matchmaker/driver/index.ts#L10) has it's own list.

2. The LocalDriver's list has a room but the matchmaker doesn't (for some buggy reason). When joining a room, that means the matchmaker tries use IPC to communicate with the (non-existent) room.

3. We aren't using a multi-process system so we hit a [timeout](https://github.com/colyseus/colyseus/blob/85bacb8068adfc215eb53c12b1f0f681ae0bbd44/packages/core/src/MatchMaker.ts#L177) when Colyseus tries to get the room from another process.

The problem here is that the matchmaker thinks a room doesn't exist but the LocalDriver does. And so the room can't be created or disposed or joined (timeouts happen because matchmaker is trying to use IPC). We're enabling the debug logs so we can add more context in the future.

## Context

People can't join one of our rooms - we get a client-side error "MatchMakeError: {{orgId}} is already full."

**Comment by ShukantPal** [comment]
We are using "@colyseus/core@0.14.24"

**Comment by lpsandaruwan** [comment]
Hi @ShukantPal 

Can you please elaborate this? Perhaps a working example setup would be great. :+1: 

> We aren't using a multi-process system so we hit a [timeout](https://github.com/colyseus/colyseus/blob/85bacb8068adfc215eb53c12b1f0f681ae0bbd44/packages/core/src/MatchMaker.ts#L177) when Colyseus tries to get the room from another process.

**Comment by german-teamflowhq** [comment]
Hey @lpsandaruwan, we just had this issue again. I hope I can clarify a bit more the problem.

Shukant's diagnosis is correct, the matchMaker cache goes out of sync with the LocalDriver's cache. Because of this, the MatchMaker tries to IPC, resulting in a timeout (we only have 1 colyseus instance). 

We looked into the code, and [this is the only place were both caches can go our of sync](https://github.com/colyseus/colyseus/blob/master/packages/core/src/MatchMaker.ts#L480-L482).
  
Additionally, we added colyseus logs, and we found that while the room was being created, it was disposed almost instantly (for some buggy reason?):
 
![Screen Shot 2022-07-15 at 16 41 23](https://user-images.githubusercontent.com/97966857/179299741-4e64d4a3-6f7f-4b27-a947-19a7f024ecae.png)

So far, the only way to reproduce it was disposing the room manually, by adding `disposeRoom(roomName, room)`  in line 306:
https://github.com/colyseus/colyseus/blob/master/packages/core/src/MatchMaker.ts#L306

You can even add some randomness, like `if (Math.random > 0.5) disposeRoom(roomName, room)`, but if you dispose it **before** saving the [LocalDriver's cache](https://github.com/colyseus/colyseus/blob/master/packages/core/src/MatchMaker.ts#L309), you will lock the room for ever. You won't even be able to dispose it from the monitor (you'll get `@colyseus/monitor: room {roomId} is not available anymore.` log).

**Comment by CookedApps** [comment]
We are currently testing Colyseus 0.15 in a multi instance setup with Redis presence and no proxy (each instance running under a unique subdomain). We are seeing the same issues as @german-teamflowhq does:

- We have a lobby room which creates a game room when the game is started. Each time this happens, the "**IPC timed out**" error gets thrown: `colyseus:errors IPC timed out. method: undefined, args: [room options...]` Interestingly, this doesn't seem to affect the game. The game room gets created and clients can connect anyway.
- **Zombie rooms** appear after a few days of operation. Inactive lobbies which still exist in the Redis presence and get listed by the matchmaker. But the rooms are non-existent.

This issue should be reopened imo.

**Comment by JCMais** [comment]
@CookedApps We actually fixed this bug on our side, more details here: https://github.com/colyseus/colyseus/issues/532#issuecomment-1220883697
