### ISSUE TITLE
Roomcount of the process not being deleted at gracefully shutdown

### ISSUE THREAD

**Issue by amit-gshe** [colyseus/colyseus#521]
When the matchmaker shutdown, it deletes the processId from the `roomcount`. It's ok in normal cases. But when creating new room in current process the matchmaker dose not check the current status of matchmaker dispite it was shutting down already.  This may lead to that the roomcount key would be added again and never be deleted.

Even worse the process won't preventing new rooms to be created in current process and this process never get stopped. 

https://github.com/colyseus/colyseus/blob/a1fca97aba30ae721bc4980935b0b257219ca44a/packages/core/src/MatchMaker.ts#L276-L281

**Comment by endel** [comment]
Interesting, thanks for reporting @amit-gshe

**Comment by CookedApps** [comment]
@endel We are still seeing this issue despite using the latest version of Colyseus (`0.15.0-preview.6`). Our `roomcount` hash is full of dead instances, all of them holding 1-3 "clients". 

This results in an `IPC timeout out` error each time we use the MatchMaker for creating a new room because it will try to use the instance with the lowest number of clients by default. Resulting in the timeout, it will fall back to the current instance.

Not sure why it doesn't get cleared on shutdown.
