### ISSUE TITLE
MatchMakeError - {{roomId}} is full

### ISSUE THREAD

**Issue by german-teamflowhq** [colyseus/colyseus#532]
This issue was [already reported](https://github.com/colyseus/colyseus/issues/513), but it was closed due to inactivity. I'm here adding more information 

## Steps to Reproduce (for bugs)

We found that if a room is disposed right after its creation, the matchMaker's cache and LocalDriver's cache goes out of sync. 
This produces that people cannot join rooms, and those rooms cannot be disposed from the monitor.
We still don't know how the room was disposed right after being created, but so far the only way to reproduce was to changing the MatchMaker code and disposing the room manually, by adding `disposeRoom(roomName, room)` in line 306:
https://github.com/colyseus/colyseus/blob/master/packages/core/src/MatchMaker.ts#L306

It has to be disposed **before** saving the [LocalDriver's cache](https://github.com/colyseus/colyseus/blob/master/packages/core/src/MatchMaker.ts#L309)

## Context
Users cannot join the room. 
The room cannot be disposed from the monitor, the only way to fix it is by restarting the server

## Your Environment
* Colyseus Version: @colyseus/core@0.14.24

**Comment by endel** [comment]
Hi @german-teamflowhq, can you provide a project that isolates and reproduces this issue you're experiencing? 

(As a maintainer, I've personally wasted countless hours just trying to reproduce user's issues, that's not something I'm gonna do anymore!)

**Comment by german-teamflowhq** [comment]
No, unfortunately the only way that I found to reproduce is by changing colyseus code. 
Based on the logs, for some reason (maybe a bug, or maybe we dispose the room), the room was disposed almost instantly:

![image](https://user-images.githubusercontent.com/97966857/182632585-4437021c-7501-41b6-acec-b7b0110cef31.png)

I'll try to create a project that reproduces this from outside of the colyseus server

**Comment by german-teamflowhq** [comment]
@endel Hope you are doing great.

We kept investigating this issue, and yesterday we found a way to reproduce this. It turns out that it was a race condition on our locking logic that avoids creating multiple rooms with the same roomId.

I'm still not sure if this was just us using the framework incorrectly, or if colyseus should be more resilient to this type of problems, so I created a [project](https://github.com/gguzelj/colyseus-room-is-full) that reproduces this issue. 

Here you will find that we have a [roomService](https://github.com/gguzelj/colyseus-room-is-full/blob/main/src/rooms/RoomsService.ts#L11) that subscribes to colyseus events, and if it founds that a duplicated room was created, it disposes it. 

The problem is that the LocalDriver's cache and the MatchMaker's cache goes out of sync, and this is because the LocalDriver is removing [rooms by reference](https://github.com/colyseus/colyseus/blob/master/packages/core/src/matchmaker/driver/RoomData.ts#L73) whereas the MatchMaker is [using the roomId](https://github.com/colyseus/colyseus/blob/master/packages/core/src/MatchMaker.ts#L494).

We already fix this issue on our end by throwing an exception from the onCreate, so feel free to close this issue.

**Comment by CookedApps** [comment]
> We already fix this issue on our end by throwing an exception from the onCreate, so feel free to close this issue.

Hey @german-teamflowhq could you please share an example on how you solved this issue? 
I'm not quite sure if I understand it correctly. 

Thanks in advance!

**Comment by CookedApps** [comment]
I've managed to fix this error on our side. It was indeed a race condition related to a `room.unlock()` call. It happened when unlock was called while the room is disposing, either through an explicit `disconnect` or implicitly through `autoDispose`. This can happen if you call them from inside an event listener. The reason for that is that `unlock()` and similar operations like `setMetadata()` update the room listing data - in our case via Redis presence. The problem is that the [presence.hset](https://docs.colyseus.io/colyseus/server/presence/#hsetkey-string-field-string-value-string) operation is used and this will recreate the key/field even if it already got removed (by disposing the room). 

**Workaround**: Avoid race conditions in the first place and check if the room is not currently disposing when setting metadata or unlocking the room. I've written this simple check for this: 
```typescript
protected willDispose() {
  return (
    this.internalState !== RoomInternalState.CREATING &&
    this.autoDispose && // could be removed
    this.clients.length === 0 &&
    Object.keys(this.reservedSeats).length === 0
  );
}
```
Use this check when setting metadata/unlocking the room:
```typescript
protected setMetadataAndHandleError(metadata: Partial<any>) {
  if (this.willDispose()) return;
  this.setMetadata(metadata).catch((reason) => this.log.error("Failed to set metadata:", reason));
}
```
Colyseus should be more robust to this type of problem. I had to dig deep into the Colyseus core code to understand what the problem was.
