### ISSUE TITLE
Crash on room dispose

### ISSUE THREAD

**Issue by MrFasolo97** [colyseus/colyseus#566]
## Steps to Reproduce (for bugs)
1.  `git clone https://github.com/MrFasolo97/colyseus-test`
2. `cd colyseus-test/server && npm i && cp config.mjs.dist config.mjs`
3. Set the config values as needed for MySQL/MariaDB database, users' table included in the repo, server folder.
4. run "node index.mjs" and then connect from the client's folder project, through defold editor,  click the "Connect" button
5. Click on the window's close button
6. The server will crash while disposing the room (I guess).

## Context
I was trying to implement an auth system through a username and a password, stored on a MySQL server.
The user will be successfully connected and authed, but when the room is disposed, the whole server crash. 
I've tried with Nodejs 16 and 18, with colyseus 0.13.x and 0.14 (the latest one), with sync and async functions. Everytime the result is the same, I might have changed something, because it was working some weeks ago, then this, but I'm not sure where to look at on colyseus code or my own code, maybe it's because my onAuth isn't as fast as needed?

Crash log:
```
🏟  Your Colyseus App
⚔️  Listening on ws://localhost:3553
[2023-05-02T18:32:53.075] [INFO] default - Room created
[2023-05-02T18:32:53.117] [DEBUG] default - test:test
[2023-05-02T18:32:53.122] [DEBUG] default - Authed
[2023-05-02T18:32:53.166] [INFO] default - Closing room :5-2eG39Z8
TypeError: Cannot read properties of undefined (reading 'emit')
    at onClientLeaveRoom (C:\Users\fasolo97\colyseus-test\server\node_modules\@colyseus\core\build\MatchMaker.js:331:29)
    at EventEmitter.emit (node:events:513:28)
    at authroom._onLeave (C:\Users\fasolo97\colyseus-test\server\node_modules\@colyseus\core\build\Room.js:502:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

## Your Environment
* Colyseus Version: ^0.14.24
* Node.js Version: v18.16.0
* Operating System and version: Windows 11
* Link to your project: https://github.com/MrFasolo97/colyseus-test (bare bone, bug reproducing project)

**Comment by endel** [comment]
Hi @MrFasolo97, 

The problem is updating the `roomName` here https://github.com/MrFasolo97/colyseus-test/blob/e9a67edbc42b57cda054a5e48829d7fe2da11135/server/rooms/authroom.mjs#L12

Room names can only be set at `gameServer.define("roomName")` 

On the upcoming version 0.15 doing this would throw an explicit error: https://github.com/colyseus/colyseus/blob/0ea7805729d81a20d884af80593c81ebb174417a/packages/core/src/Room.ts#L174-L179

BTW version 0.15 is coming out this week - it is currently available as `@preview` tag, you can install then via:
- `npm install --save colyseus@preview` (server)
- `npm install --save colyseus.js@preview` (client)

Cheers!
