### ISSUE TITLE
State serialization should be customizable 

### ISSUE THREAD

**Issue by endel** [colyseus/colyseus#58]
As suggested by @derwish-pro on https://github.com/gamestdio/colyseus/issues/48#issuecomment-307901467, it should be possible to use different serialization methods other than Fossil's Delta algorithm. 

Having this would drastically change how the clients handle state updates.

**Comment by derwish-pro** [comment]
Hi. I used jsonpatch in my project instead of the fossil delta, and msgpack. I made all changes in one commit (client and server) to make it easier to keep track of what had to change. This will help to draw attention to those parts of the code that had to change and make changes in these places. 
Just look at the diff in the last commit.

https://github.com/derwish-pro/colyseus-unity3d/tree/jsonpatch
https://github.com/derwish-pro/colyseus-jsonpatch

**Comment by endel** [comment]
Thanks @derwish-pro! I think the change you made is similar to how Colyseus v0.3.0 used to be. (The switch to Fossil's Delta algorithm was to having a smaller data throughput than JSON)

**Comment by derwish-pro** [comment]
Yes, but jsonpatch works in WebGL, and it is easier to debug than binary data. For the production version of my project I still would like to use binary data, but have not yet found a solution for this, but I will look for. And so, especially, it would be very cool to be able to switch implementations.

**Comment by endel** [comment]
We finally have this for **JavaScript** and **Defold Engine** clients: https://docs.colyseus.io/state/overview/
