### ISSUE TITLE
[Bug]: static onAuth not fired when using joinById

### ISSUE THREAD

**Issue by psociety** [colyseus/colyseus#677]
### Context

I want players to join rooms by id, so they can visit specific player houses. Since the api doesn't seem to support this case (aka having `joinOrCreateRoomById`) i built a workaround function that uses  `this.client.joinById` method.

### Bug description

The problem is that for some reason, when running `this.client.joinById(roomId);` , `OnAuth` is not fired on server side, making `OnJoin` and `OnLeave` functions not to receive `auth` field:

2 players join the same room sequentially. The first one, tester, creates the room, the second one just joins. As you can see, there's only 1 `OnAuth` message:
```
⚔️  Listening on http://localhost:2567
OnAuth
room room-1 created
tester joined room-1
bugged join :S
```
`bugged join :S` message is on `onJoin`, so `OnAuth` should have appeared in between both joins.

This is the client side:
```js
import { Client } from "colyseus.js";

export default class NetworkManager {
    client: any;
    room: any;

    constructor(userToken: string) {
        this.client = new Client("ws://localhost:2567");
        this.client.auth.token = userToken;
    }

    async joinOrCreateRoom(roomId: string) {
        console.log(this.client.auth.token);

        this.client.getAvailableRooms("my_room").then(rooms => {
            rooms.forEach((room) => {
                console.log(room.roomId, room.clients + "/" + room.maxClients);
            });
        }).catch(e => {
            console.error(e);
        });

        try {
            return await this.client.joinById(roomId);
        } catch (e) {
            console.log("creating room", e);
            return await this.client.create("my_room", {
                id: roomId
            });
        }
    }
}
```

server side MyRoom:
```js
export class MyRoom extends Room < MyRoomState > {
        maxClients = 30;

        onCreate(options: any) {
            this.roomId = options.id;
            console.log("room", this.roomId, "created");
        }

        static async onAuth(token: string, request: any) {
            console.log("OnAuth");
            return true;
        }

        onJoin(client: Client, options: any) {
            if (!client.auth) {
                console.log("bugged join :S");
                return;
            }
            console.log(client.auth.username, "joined", options.id);
        }
}
```

Code running client side:
```js
 const manager1 = new NetworkManager("eyJhbGciO....");
    manager1.room = await manager1.joinOrCreateRoom("room-1");

    const manager2 = new NetworkManager("eyJhbGciOiJIUzI...");
    manager2.room = await manager2.joinOrCreateRoom("room-1");
```
(this is a simplified example that runs 2 sockets on the same tab, but i usually work with 2 tabs and still happens).

output:
```
eyJhbGciO..... (the full auth token)
creating room Error: room "room-1" not found
eyJhbGciOiJIUzI....
room-1 1/30
```

### Steps to reproduce

1. Try to use `joinById` with `auth` system.

### Environment & Versions

Client:
```json
{
"colyseus.js": "^0.15.15",
"typescript": "^5.0.2",
"node": "v20.10.0"
}
```
OS: Windows

Server:
```json
{
    "@colyseus/monitor": "^0.15.0",
    "@colyseus/playground": "^0.15.3",
    "@colyseus/tools": "^0.15.0",
    "colyseus": "^0.15.15",
    "typescript": "^5.0.4",
    "node": "v20.10.0"
}
```
OS: Windows

I traced the problem back to this line:
https://github.com/colyseus/colyseus/blob/afceeb51d964ec0d72c958d0b8e91f4d140a332c/packages/core/src/Server.ts#L364
But i don't understand what it does, so i can't propose a fix :(

**Comment by hunkydoryrepair** [comment]
I would skip use of the `static` onAuth and continue to use the non-static onAuth for now. 
For one thing, I don't think the static version is even supported on 0.15.15 and is only available in preview builds right now (I **think**. I certainly never heard about it until well after 0.15.15 was released).

**Comment by hunkydoryrepair** [comment]
FWIW, we use `joinById` on version 0.15.15 and the non-static onAuth with no problems.

**Comment by hunkydoryrepair** [comment]
was `roomClass` defined when you tracked it down? And what was `roomName` at that point?
My assumption of what is happening here: `joinById` doesn't have a `roomName` parameter, so it cannot determine the roomClass, which will be undefined, so it cannot call the static method on the class, because it doesn't know which class to use.

As for a fix, this will either require a protocol change, where the room type is passed to `joinById`, which probably means changing the API, or the server will need to look up the roomId in the matchmaker Driver to get the room type, which is not necessarily a fast thing to do.

**Comment by hunkydoryrepair** [comment]
and, @endel, adding room type to the `joinById` endpoint will break our devops, since we use a proxy to forward the joinById to the same server that is hosting the room. We do that by adding the processId to the URL (technically, we pass `roomId/processId` to `joinById`, which then creates the URL we need to proxy it properly, but Colyseus reads just the roomId properly.  As of 0.15.15, it is probably looking up the processId as if it was a room type.

**Comment by hunkydoryrepair** [comment]
@psociety  can you try using:
```
return await this.client.joinById(`${roomId}/my_room`);
```

I think it may work if you do that

**Comment by psociety** [comment]
I've tried adding /my_room as you said and it makes no diff, this is the output if i also add a `console.log(roomClass);`:
```json
undefined (this is roomClass console.log)
[class MyRoom extends Room] (this is roomClass console.log)
OnAuth
room room-1 created
tester joined room-1
undefined (this is roomClass console.log)
bugged join :S
```

Oh, i was following the documentation that said that i should be using `static` from now on:
`Since version 0.15.14, it is preferred to use the static version onAuth() method`
If i remove static and refactor the code it seems to work!!
```
undefined  (this is roomClass console.log)
[class MyRoom extends Room]  (this is roomClass console.log)
room room-1 created
OnAuth
tester joined room-1
undefined (this is roomClass console.log)
OnAuth
tester2 joined undefined
```

**Comment by endel** [comment]
Thank you for reporting @psociety, indeed this was an oversight when designing the static `onAuth`. 

Indeed both solutions @hunkydoryrepair mentioned are not ideal, the `static onAuth` must work differently internally to allow triggering it during `joinById`. I'd suggest to continue using the instance `onAuth` for now if you require `joinById` while this is not fixed.

**Comment by hunkydoryrepair** [comment]
@endel, It appears that `joinById` ends up doing a room lookup anyway:
` const room = await driver.findOne({ roomId });`
and that has roomName.

So in terms of efficiency, one possibility is to move the static `onAuth` into the `joinById` function itself.

**Comment by psociety** [comment]
@hunkydoryrepair are you able to reliably use rooms with custom ids? I'm getting them constantly duplicated when multiple players try to join a room that has yet to be created:
```
room room-1 created
room room-1 created
Error: seat reservation expired. (either tester or tester2 got kicked and had to refresh the tab)
tester joined room-1
tester2 joined room-1
room room-1 disposing... (both players are still in the room so i'm guessing it is deleting the duplicated room)
```

**Comment by hunkydoryrepair** [comment]
@psociety  we don't use custom room IDs, but for sure multiple rooms are created if multiple players try to create it at the same time. Our approach is:
- we use `hincrby` on RedisPresence to ensure room uniqueness. We use our internal IDs that represent the area, but don't attempt to use a custom id. The onCreate throws error if the room already exists.
- we have a custom endpoint that searches for the room and creates it if it does exist. this uses the matchmaker to find an existing room with our internal-id as an option, and if it doesn't exist, create it. If the create fails, it searches again for the room. It will also clear the flag after 3 attempts of creating the room and not finding it, since other types of crashes can leave REDIS in a state that indicates it has a bad room.
- the endpoint is returned to the client, which then passes it to `joinById`
