### ISSUE TITLE
[Bug]: clients and server both get stuck if the server threw an exception

### ISSUE THREAD

**Issue by Alaadel** [colyseus/colyseus#703]
### Bug description

The server runs a js physics engine, if an exception happened in the engine, the server calls `onDispose` but doesn't accept any new clients joining.

### Reproduction

The basic unity example.

### Steps to reproduce

1. Client1 calls Join()
2. Client2 calls Join()
3. Game starts
4. Game calls a js function
5. js function throws an exception (e.g. index out of array range)
6. Server calls `ondispose`
7. Client1 leaves
8. Client2 leaves
9. Client1 and 2 cannot rejoin

### Environment & Versions

latest version

**Comment by endel** [comment]
Hi @Alaadel, that is an expected behaviour - the server-side should avoid throwing runtime exceptions.

There is a proposal to enable an exception handler within room scope going on here: https://github.com/colyseus/colyseus/pull/623
The way it was implemented it can be copy-pasted into your project. Though, this feature needs to be opt-in in case it gets incorporated into the framework.
